---
- name: Installing containerd
  apt:
    name: containerd
    state: present

- name: Enabling containerd service
  systemd: 
    name: containerd
    enabled: yes
    state: started

- name: Creating containerd configuration folder
  file:
    path: /etc/containerd
    state: directory

- name: Creating config file
  shell: touch /etc/containerd/config.toml

- name: Adding cgroups to config file
  copy:
    dest: /etc/containerd/config.toml
    content: |
      version = 2
      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          [plugins."io.containerd.grpc.v1.cri".containerd]
            [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
              [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                runtime_type = "io.containerd.runc.v2"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true

- name: Initializing configuration
  shell: systemctl start containerd

- name: SystemdCgroup enabled
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'

- name: Restarting service
  systemd: 
    name: containerd
    state: restarted

- name: Catching containerd status
  shell: systemctl status containerd | egrep Active
  register: containerdServiceStatus

- name: Current containerd service status
  debug:
    var: containerdServiceStatus.stdout_lines