# -- Addition of a host --
#
# -- Creatio of an authentication key pairts
# ssh-keygen
# ---
#
# -- Copy SSH key
# ssh-copy-id <user>@<ip>
#
# Add your IP within ansible hosts configuration
# vi /etc/ansible/hosts
#  [server]
#  <desired ip> ansible_user=<ssh user>
# ---
#
# -- Host ping
# ansible all -m ping -v
# ---
#
# -- Playbook executiom
# ansible-playbook -i <hosts inventory> -K main.yaml --tags "<tag 1>, <tag 2>, ..."
# ----
---
- hosts: server
  become: true
  roles:
    - { role: ubuntu-install-lb, tags: ['ubuntu-install-lb'] }
    - { role: ubuntu-basic-tools, tags: ['ubuntu-basic-tools'] }
    - { role: ubuntu-disable-swap, tags: ['ubuntu-disable-swap'] }
    - { role: ubuntu-ip-forwarding, tags: ['ubuntu-ip-forwarding'] }
    - { role: ubuntu-install-containerd, tags: ['ubuntu-install-containerd'] }
    - { role: ubuntu-install-kuberentes, tags: ['ubuntu-install-kuberentes'] }
    - { role: ubuntu-start-kubernetes-cluster, tags: ['ubuntu-start-kubernetes-cluster'] }
    - { role: ubuntu-install-kuberentes-worker, tags: ['ubuntu-install-kuberentes-worker'] }
    - { role: ubuntu-install-kubernetes-controller, tags: ['ubuntu-install-kubernetes-controller'] }