---
- name: Installing vim
  apt:
    name: vim
    state: present

- name: Installing tmux
  apt:
    name: tmux
    state: present

- name: Installing wget
  apt:
    name: wget
    state: present

- name: Installing curl
  apt:
    name: curl
    state: present

- name: Installing ca-certificates
  apt:
    name: ca-certificates
    state: present

- name: Installing apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Installing gpg
  apt:
    name: gpg
    state: present

